name: "Bundlewatch GitHub Action - on Tracked Branches Push"

on:
  push:
    branches:
      - master

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Borales/actions-yarn@v2.1.0
      - run: npm install
      - uses: jackyef/bundlewatch-gh-action@master
        with:
          build-script: npm run build
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}