name: "Bundlewatch GitHub Action - on Tracked Branches Push"

on:
  pull_request:
    types: [opened, synchronize]


jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Bundlesize
        run: npm run bundle
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}